export const colorClasses = {
  "transparent": "transparent",
  "current": "currentColor",
  'primary': 'oklch(var(--primary)/<alpha-value>)',
  'primary-content': 'oklch(var(--primary-content)/<alpha-value>)',
  'secondary': 'oklch(var(--secondary)/<alpha-value>)',
  'secondary-content': 'oklch(var(--secondary-content)/<alpha-value>)',
  'accent': 'oklch(var(--accent)/<alpha-value>)',
  'accent-content': 'oklch(var(--accent-content)/<alpha-value>)',
  'info': 'oklch(var(--info)/<alpha-value>)',
  'info-content': 'oklch(var(--info-content)/<alpha-value>)',
  'success': 'oklch(var(--success)/<alpha-value>)',
  'success-content': 'oklch(var(--success-content)/<alpha-value>)',
  'warning': 'oklch(var(--warning)/<alpha-value>)',
  'warning-content': 'oklch(var(--warning-content)/<alpha-value>)',
  'error': 'oklch(var(--error)/<alpha-value>)',
  'error-content': 'oklch(var(--error-content)/<alpha-value>)',
  'layer': 'oklch(var(--layer)/<alpha-value>)',
  'layer-content': 'oklch(var(--layer-content)/<alpha-value>)',
};
